const benefits=[['🏛️','Representatividade institucional','Fortalecimento do setor perante mercado, órgãos públicos e entidades parceiras.'],['📄','Comunicados e documentos','Estatutos, atas, circulares, manuais e orientações centralizados.'],['📅','Eventos e assembleias','Participação em encontros, reuniões, assembleias e capacitações.'],['📣','Divulgação da empresa associada','Vitrine pública para ampliar presença digital e oportunidades comerciais.'],['💬','Canal direto','Solicitações, suporte e mensagens com histórico organizado.'],['🔌','Integrações futuras','Boleto, Pix, WhatsApp, WooCommerce e plugins de membership.']];
const members=[['Minas Fretamento Executivo','Belo Horizonte','RMBH','Fretamento executivo'],['Turismo Serra Verde','Contagem','RMBH','Turismo'],['Expresso Estrada Real','Ouro Preto','Central','Turismo receptivo'],['Van Minas Corporate','Betim','RMBH','Transporte corporativo'],['Fretur Viagens','Juiz de Fora','Zona da Mata','Viagens e excursões'],['Rotas Gerais Turismo','Montes Claros','Norte de Minas','Turismo rodoviário']];
const docs=['Estatuto AMIFRET','Ata de Assembleia','Circular para Associados','Orientações sobre Fretamento','Manual do Associado'];
const comms=['Convocação para reunião','Atualização sobre legislação','Novo canal de atendimento','Campanha institucional'];
const events=['Reunião de Diretoria','Assembleia Geral','Encontro de Associados','Palestra sobre Mobilidade e Turismo'];
const adminRows=[['Minas Fretamento Executivo','Belo Horizonte','RMBH','Ativo','Profissional'],['Turismo Serra Verde','Contagem','RMBH','Ativo','Essencial'],['Expresso Estrada Real','Ouro Preto','Central','Pendente','Profissional'],['Fretur Viagens','Juiz de Fora','Zona da Mata','Suspenso','Essencial'],['Rotas Gerais Turismo','Montes Claros','Norte de Minas','Ativo','Profissional']];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function modal(title,text){$('#modalContent').innerHTML=`<h2>${title}</h2><p>${text}</p>`;$('#modal').classList.add('show');$('#modal').setAttribute('aria-hidden','false')}
function initLanding(){benefitCards.innerHTML=benefits.map(b=>`<article class="info-card"><span>${b[0]}</span><h3>${b[1]}</h3><p>${b[2]}</p></article>`).join('');['city','region','service'].forEach((kind,i)=>{const sel=$(`#${kind}Filter`);[...new Set(members.map(m=>m[i+1]))].forEach(v=>sel.insertAdjacentHTML('beforeend',`<option>${v}</option>`));sel.addEventListener('change',renderMembers)});renderMembers()}
function renderMembers(){const c=cityFilter.value,r=regionFilter.value,s=serviceFilter.value;memberGrid.innerHTML=members.filter(m=>(!c||m[1]==c)&&(!r||m[2]==r)&&(!s||m[3]==s)).map(m=>`<article class="member-card"><div class="member-logo">${m[0].split(' ').map(x=>x[0]).slice(0,2).join('')}</div><h3>${m[0]}</h3><p>${m[1]} • ${m[2]}</p><div class="tags"><span class="tag">${m[3]}</span><span class="tag">Associado ativo</span></div><button class="small-btn" onclick="modal('${m[0]}','Empresa demonstrativa associada à AMIFRET em ${m[1]}, região ${m[2]}, com atuação em ${m[3]}.')">Ver detalhes</button></article>`).join('')}
function showPage(id){$$('.page').forEach(p=>p.classList.remove('active'));const page=$('#'+id)||$('#home');page.classList.add('active');if(id==='portal')renderPortal('Dashboard');if(id==='admin')renderAdmin('Dashboard');scrollTo(0,0);$$('.nav-links').forEach(n=>n.classList.remove('open'))}
function route(){const h=location.hash.replace('#','');if(['login','portal','admin'].includes(h))showPage(h);else{showPage('home');if(h)setTimeout(()=>document.getElementById(h)?.scrollIntoView(),50)}}
function side(items,active,fn){return `<aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">A</span><span>AMIFRET</span></a><nav class="side-menu">${items.map(i=>`<button class="${i===active?'active':''}" onclick="${fn}('${i}')">${i}</button>`).join('')}</nav></aside>`}
function renderPortal(active){const menu=['Dashboard','Minha empresa','Documentos','Comunicados','Agenda','Mensalidades','Suporte / WhatsApp','Sair'];let body='';if(active==='Dashboard')body=`<div class="topbar"><h1>Bem-vindo, Minas Fretamento Executivo</h1><span class="tag">Associado ativo</span></div><div class="stats-grid">${[['Status','Associado ativo'],['Próxima mensalidade','R$ 350,00'],['Vencimento','10/08/2026'],['Documentos disponíveis','8'],['Comunicados não lidos','3']].map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('')}</div><div class="panel"><h2>Resumo do portal</h2><p>Consulte documentos, comunicados, agenda e mensalidades em um ambiente centralizado para membros da AMIFRET.</p></div>`;
if(active==='Minha empresa')body=`<h1>Minha empresa</h1><div class="panel"><div class="table-wrap"><table class="table"><tbody>${[['Razão social','Minas Fretamento Executivo Ltda.'],['Nome fantasia','Minas Fretamento Executivo'],['CNPJ','12.345.678/0001-90'],['Cidade','Belo Horizonte'],['Região','RMBH'],['Telefone','(31) 3333-4400'],['E-mail','contato@minasfretamento.com.br'],['Site','www.minasfretamento.com.br'],['Logo','Placeholder AMIFRET'],['Status de exibição pública','Ativo na vitrine pública']].map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td></tr>`).join('')}</tbody></table></div><br><button class="btn btn-primary" onclick="modal('Atualização cadastral','Solicitação de atualização cadastral registrada em modo demonstração.')">Solicitar atualização cadastral</button></div>`;
if(active==='Documentos')body=`<h1>Documentos</h1><div class="doc-list">${docs.map((d,i)=>`<article class="doc-item"><div><h3>${d}</h3><p>Categoria: Institucional • Data: ${String(i+3).padStart(2,'0')}/07/2026</p></div><div class="doc-actions"><button class="small-btn" onclick="modal('${d}','Visualização demonstrativa do documento.')">Visualizar</button><button class="small-btn" onclick="modal('${d}','Download demonstrativo iniciado.')">Baixar</button></div></article>`).join('')}</div>`;
if(active==='Comunicados')body=`<h1>Comunicados</h1><div class="doc-list">${comms.map(c=>`<article class="doc-item"><div><h3>${c}</h3><p>Comunicado para associados • Não lido</p></div><button class="small-btn" onclick="modal('${c}','Detalhes demonstrativos do comunicado enviado pela AMIFRET aos associados.')">Abrir</button></article>`).join('')}</div>`;
if(active==='Agenda')body=`<h1>Agenda</h1><div class="event-list">${events.map((e,i)=>`<article class="event-card"><span class="tag">${10+i*5}/08/2026</span><h3>${e}</h3><p>Evento demonstrativo com inscrição e confirmação futura pelo portal.</p></article>`).join('')}</div>`;
if(active==='Mensalidades')body=`<h1>Mensalidades</h1><div class="panel"><h2>Mensalidade atual</h2><p><b>Valor:</b> R$ 350,00 • <b>Status:</b> em aberto • <b>Vencimento:</b> 10/08/2026</p><div class="hero-actions"><button class="btn btn-primary" onclick="modal('Boleto','Boleto gerado em modo demonstração')">Gerar boleto</button><button class="btn btn-secondary" onclick="modal('Pix','QR Code Pix demonstrativo')">Pagar via Pix</button><button class="btn btn-secondary" onclick="modal('WhatsApp','Mensagem de WhatsApp simulada')">Enviar lembrete pelo WhatsApp</button></div></div>`;
if(active==='Suporte / WhatsApp')body=`<h1>Suporte / WhatsApp</h1><div class="panel"><p>Canal demonstrativo para atendimento aos associados.</p><button class="btn btn-primary" onclick="modal('Suporte','Mensagem enviada ao suporte em modo demonstração.')">Abrir atendimento</button></div>`;
if(active==='Sair'){location.hash='login';return}portal.innerHTML=`<div class="dashboard">${side(menu,active,'renderPortal')}<section class="content">${body}</section></div>`}
function renderAdmin(active){const menu=['Dashboard','Associados','Documentos','Comunicados','Agenda','Solicitações','Configurações'];let body='';if(active==='Dashboard')body=`<h1>Dashboard Admin</h1><div class="stats-grid">${[['Total de associados','180'],['Associados ativos','162'],['Pendentes','12'],['Suspensos','6'],['Documentos publicados','24'],['Comunicados enviados','15']].map(x=>`<article class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('')}</div>`;
if(active==='Associados')body=`<div class="topbar"><h1>Associados</h1><button class="btn btn-primary" onclick="modal('Novo associado','Formulário demonstrativo aberto para cadastro completo de associado.')">Novo associado</button></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Nome fantasia</th><th>Cidade</th><th>Região</th><th>Status</th><th>Plano</th><th>Ações</th></tr></thead><tbody>${adminRows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="status ${r[3]==='Ativo'?'ok':r[3]==='Pendente'?'warn':'bad'}">${r[3]}</span></td><td>${r[4]}</td><td>editar • visualizar • suspender</td></tr>`).join('')}</tbody></table></div><form class="panel admin-form"><h2>Cadastro de associado</h2>${['Razão social','Nome fantasia','CNPJ','Responsável','E-mail','Telefone','WhatsApp','Cidade','Região','Site','Status','Aparece na vitrine pública: sim/não'].map(x=>`<label>${x}<input></label>`).join('')}<button type="button" class="btn btn-primary" onclick="modal('Cadastro','Associado salvo em modo demonstração.')">Salvar</button></form>`;
if(active==='Documentos')body=`<h1>Documentos</h1><form class="panel admin-form"><h2>Upload simulado</h2><label>Título<input></label><label>Categoria<input></label><label>Visibilidade<select><option>público</option><option>associados</option><option>diretoria</option></select></label><label>Data de publicação<input type="date"></label><button type="button" class="btn btn-primary" onclick="modal('Documento','Documento publicado em modo demonstração.')">Publicar documento</button></form>`;
if(active==='Comunicados')body=`<h1>Comunicados</h1><form class="panel admin-form"><label>Título<input></label><label>Texto<textarea rows="5"></textarea></label><label>Público-alvo<select><option>todos</option><option>ativos</option><option>pendentes</option><option>diretoria</option></select></label><button type="button" class="btn btn-primary" onclick="modal('Comunicado','Comunicado publicado em modo demonstração.')">Publicar</button></form>`;
if(!body)body=`<h1>${active}</h1><div class="panel"><p>Módulo administrativo demonstrativo preparado para evolução futura.</p></div>`;admin.innerHTML=`<div class="dashboard">${side(menu,active,'renderAdmin')}<section class="content">${body}</section></div>`}
$('.menu-toggle').addEventListener('click',e=>{const m=$('#main-menu');m.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',m.classList.contains('open'))});$('#loginForm').addEventListener('submit',e=>{e.preventDefault();location.hash='portal'});$('#joinForm').addEventListener('submit',e=>{e.preventDefault();$('#joinSuccess').classList.add('show');e.target.reset()});$('.modal-close').addEventListener('click',()=>$('#modal').classList.remove('show'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')});addEventListener('hashchange',route);initLanding();route();
